format_version: v1.0
type: UniqueComponent
attributes: {id: tflite-micro}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/BITS.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FFT.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FFT.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FFT_UTIL.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FFT_UTIL.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FILTERBANK.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FILTERBANK.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FILTERBANK_UTIL.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FILTERBANK_UTIL.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FRONTEND.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FRONTEND.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FRONTEND_UTIL.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/FRONTEND_UTIL.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/KISS_FFT_COMMON.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/KISS_FFT_INT16.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/LOG_LUT.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/LOG_LUT.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/LOG_SCALE.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/LOG_SCALE.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/LOG_SCALE_UTIL.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/LOG_SCALE_UTIL.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/NOISE_REDUCTION.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/NOISE_REDUCTION.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/NOISE_REDUCTION_UTIL.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/NOISE_REDUCTION_UTIL.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/PCAN_GAIN_CONTROL.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/PCAN_GAIN_CONTROL.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/PCAN_GAIN_CONTROL_UTIL.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/PCAN_GAIN_CONTROL_UTIL.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/WINDOW.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/WINDOW.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/WINDOW_UTIL.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE-MICRO/TENSORFLOW/LITE/EXPERIMENTAL/MICROFRONTEND/LIB/WINDOW_UTIL.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE/THIRD_PARTY/KISSFFT/KISS_FFT.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE/THIRD_PARTY/KISSFFT/KISS_FFT.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE/THIRD_PARTY/KISSFFT/KISS_FFT_LOG.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE/THIRD_PARTY/KISSFFT/TOOLS/KISS_FFTR.C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE/THIRD_PARTY/KISSFFT/TOOLS/KISS_FFTR.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TFLITE/THIRD_PARTY/KISSFFT/_KISS_FFT_GUTS.H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: USE_KISSFFT_LIBRARY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tflite-micro, value: 'true'}
  - type: Boolean
    attributes: {id: USE_MICROFRONTEND_LIBRARY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Setting
    attributes: {id: XC32CPP_TFLITE_FIXED_POINT_MACRO}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: FIXED_POINT=16}
  - type: Setting
    attributes: {id: XC32_TFLITE_FIXED_POINT_MACRO}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: value}
        children:
        - {type: Value, value: FIXED_POINT=16}
- type: ElementPosition
  attributes: {x: '700', y: '19', id: tflite-micro}
