configName: sam_e54_xpro
folderName: sam_e54_xpro
format_version: v1.0
frameworkPath: ..\..\..\..
processor: ATSAME54P20A
projectName: hello_world_sam_e54_xpro
settings:
  PackageFilter: aerospace;audio;aws_cloud;azure-rtos-threadx;bootloader;bsp;bt;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;ethercat;gfx;gfx_apps;micrium_ucos3;motor_control;net;tflite;touch;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.4.70\atdf\ATSAME54P20A.atdf
