format_version: v1.0
type: UniqueComponent
attributes: {id: TensorFlowLite}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/ADD.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/CMSIS-NN/ADD.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/CMSIS-NN/CONV.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/CMSIS-NN/DEPTHWISE_CONV.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/CMSIS-NN/FULLY_CONNECTED.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/CMSIS-NN/MUL.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/CMSIS-NN/POOLING.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/CMSIS-NN/SOFTMAX.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/CONV.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/DEPTHWISE_CONV.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/FULLY_CONNECTED.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/MUL.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/POOLING.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: ../TENSORFLOW/TENSORFLOW/LITE/MICRO/KERNELS/SOFTMAX.CC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TFLITE_USES_CMSIS_NN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Setting
    attributes: {id: XC32CPP_TFLITE_CMSIS_NN_MACRO}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Setting
    attributes: {id: XC32_TFLITE_CMSIS_NN_MACRO}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '720', y: '20', id: TensorFlowLite}
