format_version: v1.0
type: UniqueComponent
attributes: {id: tflite-micro}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TFLITE_USES_CMSIS_NN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '63', y: '70', id: tflite-micro}
