configName: sam_e70_xult_imu2
folderName: sam_e70_xult_imu2
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAME70Q21B
projectName: magic_wand_sam_e70_xult_imu2
settings:
  PackageFilter: audio;bsp;core;csp;dev_packs;gfx;motor_control;quick_docs;tflite;touch;usb;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.6.98\same70b\atdf\ATSAME70Q21B.atdf
